title: Nick Swetlin
author: Nick Swetlin # shown in footer

description: "My personal website."
remote_theme: nrandecker/particle
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#### BELOW IS BEAUTIFUL JEKYLL CONFIGS ####

###############################################
# --- List of links in the navigation bar --- #
###############################################

# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "/nickswetlin" # the subpath of your site, e.g. /blog/
url: "http://nickswetlin.github.io" # the base hostname & protocol for your site

# User settings
username: Nick Swetlin
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Anon Developer
email: nickswetlin@gmail.com
github_username:  nickswetlin
linkedin: nickswetlin
