

title: Nick Swetlin
email: nickswetlin@gmail.com
description: >-
  Very good my site is!
baseurl: /nickswetlin
url: https://nickswetlin.github.io/
github_username: nickswetlin

# Build settings
theme: minima
plugins:
  - jekyll-feed
