remote_theme: nrandecker/particle
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#### BELOW IS PARTICLE JEKYLL CONFIGS ####

# Site settings
description: My personal website.
baseurl: "/nickswetlin" # the subpath of your site, e.g. /blog/
url: "http://nickswetlin.github.io" # the base hostname & protocol for your site

# User settings
username: Nick Swetlin
user_description: I love talking and I love data.
user_title: Data Scientist
email: nickswetlin@gmail.com
github_username:  nickswetlin
linkedin: nickswetlin
