
# Site settings
title: Nick Swetlin
description: My personal website.
baseurl: "/nickswetlin" # the subpath of your site
url: "https://nickswetlin.github.io" # the base hostname & protocol for your site

# User settings
username: Nick Swetlin
user_description: A strong analyst with an extensive background in public communications.
user_title: Data Scientist
email: nickswetlin@gmail.com
github_username: nickswetlin

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']


